name: Docker

on: push

env:
  # # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io
  # # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}
  # tests
  IMAGE_TAG: ${{ github.repository }}:gh-action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # # Login against a Docker registry except on PR
      # # https://github.com/docker/login-action
      # - name: Log into registry ${{ env.REGISTRY }}
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # Build and export Docker image for tests
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_TAG }}

      # Generate PDF from docs
      - name: Generate PDF
        run: |
          docker run --rm \
          --cap-add=SYS_ADMIN \
          --user "$(id -u):$(id -g)" \
          -v "$(pwd)/docs:/home/node/docs:ro" \
          -v "$(pwd)/pdf:/home/node/pdf:rw" \
          -v "$(pwd)/resources/covers/cover.pdf:/home/node/resources/cover.pdf:ro" \
          -e "PDF_OUTPUT_NAME=career-docs.pdf" \
          ${{ env.IMAGE_TAG }}

      - uses: actions/upload-artifact@v4
        with:
          name: career-docs-pdf
          path: pdf/*.pdf
